## Pytorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Creating tensors

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
## TENSOR

TENSOR = torch.tensor([[[1,23,32],
                        [13241,3214,12332],
                        [213412,13231,1323]]])
TENSOR

tensor([[[     1,     23,     32],
         [ 13241,   3214,  12332],
         [213412,  13231,   1323]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[     1,     23,     32],
        [ 13241,   3214,  12332],
        [213412,  13231,   1323]])

### Random Tensor

The neural networks learn through random numbers and then adust random numbers to fit the data

In [16]:
## Create Random tensor

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1996, 0.1540, 0.7716, 0.3156],
        [0.5376, 0.7676, 0.3051, 0.8156],
        [0.6669, 0.0513, 0.8917, 0.6993]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # colour channel, height, width
random_image_size_tensor.shape,random_image_size_tensor.ndim


(torch.Size([3, 224, 224]), 3)

In [19]:
# Tensor of zeroes
zero = torch.zeros(3,4)

In [20]:
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Tensor of ones

ones = torch.ones(3,4)

In [22]:
ones.dtype

torch.float32

In [23]:
### Create a range of tensors and tensors-like
range_tensor = torch.arange(start = 0,end =1000, step= 100)
range_tensor

tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [24]:
### Creating tensors like
ten_zeroes = torch.zeros_like(range_tensor)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Datatypes

In [25]:
float_32 = torch.tensor([3,6,9],dtype=torch.float32, # datatype of tensor
                        device=None, # Specify the device CPU or GPU
                        requires_grad=False) # Whether gradient should be kept in track or not

In [26]:
float_32.dtype

torch.float32

In [27]:
float_16 = float_32.type(torch.float16)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
int_32 = torch.tensor([3,6,9],dtype=torch.int32)

In [29]:
float_32 * int_32

tensor([ 9., 36., 81.])

In [30]:
t = torch.rand(3,4)

In [31]:
print(f"Datatype: {t.dtype}")
print(f"Size: {t.size()}")
print(f"Shape: {t.shape}")
print(f"Device: {t.device}")

Datatype: torch.float32
Size: torch.Size([3, 4])
Shape: torch.Size([3, 4])
Device: cpu


### Matrix multiplication

2 types

Element wise and matrix multiplication

In [32]:
# Element wise multiplication

print(f"{t *t}")

tensor([[1.0937e-01, 1.7489e-01, 8.0671e-01, 1.6299e-02],
        [4.2565e-03, 9.4029e-01, 5.6441e-03, 5.2010e-01],
        [8.2979e-02, 5.5540e-01, 4.2416e-01, 4.5055e-04]])


In [33]:
torch.matmul(float_32,float_32)

tensor(126.)

Shape error is when dimensions dont match. The inner dimensions of the matrix should match

In [34]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])

In [35]:
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])

In [36]:
## this is also matrix multiplication
#torch.mm(tensor_A,tensor_B)

# Will not work because of the dimension mismatch

In [37]:
tensor_B.shape

torch.Size([3, 2])

Manipulation of shapes using Transpose

In [38]:
tensor_B.T.shape

torch.Size([2, 3])

In [39]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Tensor Aggregation

finding min,max,mean,sum etc

In [40]:
# Create a tensor

x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [41]:
x.dtype

torch.int64

In [42]:
# Min
x.min()

tensor(1)

In [43]:
## Max
x.max()

tensor(91)

In [44]:
# Mean
## Changing the type because it doesn't work on long
torch.mean(x.type(torch.float32))

tensor(46.)

In [45]:
# Sum
torch.sum(x),x.sum()

(tensor(460), tensor(460))

In [46]:
## Finding the positional min and max
x.argmin()

tensor(0)

In [47]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing


* Reshape- Reshapes the tensor
* View - Return the view of an input tensor of certain shape but keep the same memory as the original
* Stacking - Combine the multiple tensors in whatever dimension we need
* Squeeze - Removes all `1` dimensions from a tensor
* Unsqueeze - Adds all `1` dimensions from a tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [48]:
 import torch
 x = torch.arange(1.,10.)
 x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [49]:
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [50]:
x_reshaped = x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [51]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

Note: Changing z changes X because a view of a tensor shares the same memory as the original element

In [52]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [53]:
## Stack tensors

x_stacked = torch.stack([x,x,x,x],dim = 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [54]:
# Squeeze

x_reshaped.shape

torch.Size([9, 1])

In [55]:
x_squeezed = x_reshaped.squeeze()

In [56]:
x_squeezed.shape

torch.Size([9])

In [57]:
## Unsqueeze
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Unsqueezing
x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f"New tensor: {x_unsqueezed}")
print(f"Current shape: {x_unsqueezed.shape}")


Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Current shape: torch.Size([1, 9])


In [58]:
# Permute

x_original = torch.rand(224,224,3)

# Permute the original tensor to rearrange the axis or dim

x_permuted = x_original.permute(2,0,1)

print(f"Original shape {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Original shape torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [59]:
x_original[0,0,0] = 12

In [60]:
x_original[0,0,0],x_permuted[0,0,0]

(tensor(12.), tensor(12.))

In [61]:
## Indexing

a = torch.arange(1,10).reshape(1,3,3)
a,a.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [62]:
a[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [63]:
a[0][0]

tensor([1, 2, 3])

In [64]:
a[0,0]

tensor([1, 2, 3])

In [65]:
a[0][1][1]

tensor(5)

In [66]:
a[0][2][2]

tensor(9)

In [67]:
a[:,0]

tensor([[1, 2, 3]])

In [68]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dim

a[:,:,1]

tensor([[2, 5, 8]])

In [69]:
a[:,1,1]

tensor([5])

In [70]:
a[0,0,:]

tensor([1, 2, 3])

In [71]:
a[0][2][2]

tensor(9)

In [72]:
a[:,:,2]

tensor([[3, 6, 9]])

In [73]:
# Pytorch tensors & Numpy

## Converting to numpy
a = a.numpy()

In [74]:
## Converting to pytorch
tensor = torch.from_numpy(a)


In [75]:
## Reproducibility
 # Use random seed
random_seed = 123
torch.manual_seed(random_seed)
b= torch.rand(3,4)

torch.manual_seed(random_seed)
c = torch.rand(3,4)

b == c

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [76]:
torch.cuda.is_available()

True